IF EXISTS (SELECT TOP 1 1 FROM [SYS].[OBJECTS] WHERE [OBJECT_ID] = OBJECT_ID(N'[dbo].[QPackRPack_PackageStatistics]') AND [TYPE] in (N'U'))
    DROP TABLE [dbo].[QPackRPack_PackageStatistics]
GO
CREATE TABLE [dbo].[QPackRPack_PackageStatistics]
(
    [ID] BIGINT IDENTITY(1,1) NOT NULL,
    [ScheduleID] BIGINT NOT NULL,
    [TestCenterID] BIGINT NOT NULL,
    [PackageType] NVARCHAR(10) NOT NULL,
    [GeneratedDate] DATETIME NOT NULL,
    [TransferredToDataExchangeServer] BIT CONSTRAINT DF_TransferredToDataExchangeServer DEFAULT(0),
    [TransferredToDataExchangeServerOn] DATETIME,
    [TransferredToTestCenter] BIT CONSTRAINT DF_TransferredToTestCenter DEFAULT(0),
    [TransferredToTestCenterOn] DATETIME,
    [TransferredToDataCenter] BIT CONSTRAINT DF_TransferredToDataCenter DEFAULT(0),
    [TransferredToDataCenterOn] DATETIME,
    [RecievedFromDataExchangeServer] BIT CONSTRAINT DF_RecievedFromDataExchangeServer DEFAULT(0),
    [RecievedFromDataExchangeServerOn] DATETIME,
    [RecievedFromTestCenter] BIT CONSTRAINT DF_RecievedFromTestCenter DEFAULT(0),
    [RecievedFromTestCenterOn] DATETIME,
    [RecievedFromDataCenter] BIT CONSTRAINT DF_RecievedFromDataCenter DEFAULT(0),
    [RecievedFromDataCenterOn] DATETIME,
    [PackageName] NVARCHAR(MAX),
    [PackagePassword] NVARCHAR(MAX),
    [PackagePath] NVARCHAR(MAX),
	[OrganizationID] [bigint] NULL,
	[OrganizationName] [nvarchar](max) NULL,
	[DivisionID] [bigint] NULL,
	[DivisionName] [nvarchar](max) NULL,
	[ProcessID] [bigint] NULL,
	[ProcessName] [nvarchar](max) NULL,
	[EventID] [bigint] NULL,
	[EventName] [nvarchar](max) NULL,
	[BatchID] [bigint] NULL,
	[BatchName] [nvarchar](max) NULL,
	[TestCenterName] [nvarchar](max) NULL,
	[ScheduleDate] [datetime] NULL,
	[ScheduleStartDate] [datetime] NULL,
	[ScheduleEndDate] [datetime] NULL,
	[LeadTimeForQPackDispatchInMinutes] [int] NULL CONSTRAINT [DF_LeadTimeForQPackDispatchInMinutes]  DEFAULT ((0)),
	[DeleteQPackAfterExamination] [bit] NULL CONSTRAINT [DF_DeleteQPackAfterExamination]  DEFAULT ((0)),
	[RPackToBeSentImmediatelyAfterExamination] [bit] NULL CONSTRAINT [DF_RPackToBeSentImmediatelyAfterExamination]  DEFAULT ((0)),
	[RPackToBeSentAtEOD] [bit] NULL CONSTRAINT [DF_RPackToBeSentAtEOD]  DEFAULT ((0)),
	[DeleteRPackAfterExamination] [bit] NULL CONSTRAINT [DF_DeleteRPackAfterExamination]  DEFAULT ((0)),
	[DeleteRPackAtEOD] [bit] NULL CONSTRAINT [DF_DeleteRPackAtEOD]  DEFAULT ((0)),
	[PackageDeletedStatus] [bit] NULL CONSTRAINT [DF_PackageDeletedStatus]  DEFAULT ((0)),
	[IsCentralizedPackage] [bit] NOT NULL CONSTRAINT [DF_QPackRPack_PackageStatistics_IsCentralizedPackage]  DEFAULT ((0)),
	[Extension1] [nvarchar](max) NULL,
	[Extension2] [nvarchar](max) NULL,
	[Extension3] [nvarchar](max) NULL,
	[Extension4] [nvarchar](max) NULL,
	[Extension5] [nvarchar](max) NULL,
	[ScheduleDetailID] [bigint] NULL
)
GO