namespace Saras.eMarking.Domain.ViewModels.AuditTrail
{
    public enum AuditTrailModule
    {
        [StringValue("PROJECTSETUP")]
        PROJECTSETUP,
        [StringValue("BASICDETAILS")]
        BASICDETAILS,
        [StringValue("QIGSETUP")]
        QIGSETUP,
        [StringValue("STDSETTINGS")]
        STDSETTINGS,
        [StringValue("PROJECTSCHEDULE")]
        PROJECTSCHEDULE,
        [StringValue("PROLVLCONFIG")]
        PROLVLCONFIG,
        [StringValue("STANDARDISATION")]
        STANDARDISATION,
        [StringValue("SETUP")]
        SETUP,
        [StringValue("RECMND")]
        RECMND,
        [StringValue("TRIALMRKNG")]
        TRIALMRKNG,
        [StringValue("CATEGORISATION")]
        CATEGORISATION,
        [StringValue("QACREATION")]
        QACREATION,
        [StringValue("MARKSCHEMELIB")]
        MARKSCHEMELIB,
        [StringValue("QUESTIONS")]
        QUESTIONS,
        [StringValue("DASHBOARD")]
        DASHBOARD,
        [StringValue("RCOI")]
        RCOI,
        [StringValue("S2S3APPROVAL")]
        S2S3APPROVAL,
        [StringValue("USERLOGIN")]
        USERLOGIN,
        [StringValue("QIGMANAGEMENT")]
        QIGMANAGEMENT,
        [StringValue("LIVEMARKING")]
        LIVEMARKING,
        [StringValue("PASSPHRASE")]
        PASSPHRASE, 
        [StringValue("APPLICATIONUSERMANAGEMENT")]
        APPLICATIONUSERMANAGEMENT,
        [StringValue("CANDIDATEWITHDRAW")]
        CANDIDATEWITHDRAW,
        [StringValue("PROJECTUSERMANAGEMENT")]
        PROJECTUSERMANAGEMENT,
        [StringValue("QUALITYCHECK")]
        QUALITYCHECK,
        [StringValue("AUTOMATIC")]
        AUTOMATIC,
        [StringValue("SEMIAUTOMATIC")]
        SEMIAUTOMATIC,
        [StringValue("DATAREPORT")]
        DATAREPORT,
        [StringValue("OUTBOUNDREPORTS")]
        OUTBOUNDREPORTS,
       [StringValue("STUDENTREPORTS")]
        STUDENTREPORTS,
        [StringValue("PROJECTCLOSURE")]
        PROJECTCLOSURE,
        [StringValue("QIGTEAMMANAGEMENT")]
        QIGTEAMMANAGEMENT,
             [StringValue("REPORTS")]
        REPORTS

    }
}
