namespace Saras.eMarking.Domain.ViewModels.AuditTrail
{
    public enum AuditTrailEvent
    {
        [StringValue("CREATE")]
        CREATE,
        [StringValue("UPDATE")]
        UPDATE,
        [StringValue("DELETE")]
        DELETE,
        [StringValue("COMPLETED")]
        COMPLETED,
        [StringValue("ASSIGN")]
        ASSIGN,
        [StringValue("EVALUATED")]
        EVALUATED,
        [StringValue("LOGIN")]
        LOGIN,
        [StringValue("IMPORT")]
        IMPORT,
        [StringValue("COPY")]
        COPY,
        [StringValue("MOVE")]
        MOVE,
        [StringValue("CANCEL")]
        CANCEL,
        [StringValue("SAVE")]
        SAVE,
        [StringValue("AUTOSAVE")]
        AUTOSAVE,
        [StringValue("ACTION")]
        ACTION,
        [StringValue("VIEW")]
        VIEW,
        [StringValue("SUBMIT")]
        SUBMIT,
        [StringValue("EXPORT")]
        EXPORT,
        [StringValue("TAGUSERS")]
        TAGUSERS,
        [StringValue("EXPORTPDF")]
        EXPORTPDF,
        [StringValue("HISTORY")]
        HISTORY,
        [StringValue("EDIT")]
        EDIT,
        [StringValue("ARCHIVE")]
        ARCHIVE,
        [StringValue("DISCARD")]
        DISCARD,
        [StringValue("UNTAGUSERS")]
        UNTAGUSERS,
        [StringValue("PREVIEW")]
        PREVIEW,
        [StringValue("BLOCKUSER")]
        BLOCKUSER,
        [StringValue("PASSAGE")]
        PASSAGE,
        [StringValue("CLEAR")]
        CLEAR,
        [StringValue("REFRESH")]
        REFRESH,
        [StringValue("PAUSEQIG")]
        PAUSEQIG,
        [StringValue("RESUMEQIG")]
        RESUMEQIG,
        [StringValue("PROMOTED")]
        PROMOTED,
        [StringValue("INPROGRESS")]
        INPROGRESS,
        [StringValue("DECLINEDORSUSPENDED")]
        DECLINEDORSUSPENDED,
        [StringValue("PENDING")]
        PENDING,
        [StringValue("SAVEASDRAFT")]
        SAVEASDRAFT,
        [StringValue("NAVIGATION")]
        NAVIGATION,
        [StringValue("SCHEDULENOTIIFCATION")]
        SCHEDULENOTIIFCATION,
        [StringValue("PROJECTVIEW")]
        PROJECTVIEW,
        [StringValue("APPROVE")]
        APPROVE,
        [StringValue("REJECT")]
        REJECT,
        [StringValue("RECATEGORISATION")]
        RECATEGORISATION,
        [StringValue("LOGOUT")]
        LOGOUT,
        [StringValue("FORGOTPASSWORD")]
        FORGOTPASSWORD,
        [StringValue("CHANGEPASSWORD")]
        CHANGEPASSWORD, 
        [StringValue("DOWNLOAD")]
        DOWNLOAD,
        [StringValue("UNBLOCKUSER")]
        UNBLOCKUSER, 
        [StringValue("GRACEPERIOD")]
        GRACEPERIOD,
        [StringValue("WITHDRAW")]
        WITHDRAW,
        [StringValue("ACTIVE")]
        ACTIVE,
        [StringValue("INACTIVE")]
        INACTIVE,
        [StringValue("ENABLE")]
        ENABLE,
        [StringValue("DISABLE")]
        DISABLE,
        [StringValue("MAP")]
        MAP,
        [StringValue("UNMAP")]
        UNMAP,
        [StringValue("RESET")]
        RESET,
        [StringValue("FINALISE")]
        FINALISE,
        [StringValue("CHECKEDOUT")]
        CHECKEDOUT,
        [StringValue("TAG")]
        TAG,
        [StringValue("RETAG")]
        RETAG,
        [StringValue("UPLOADTOIEXAM2")]
        UPLOADTOIEXAM2,
        [StringValue("UPLOAD")]
        UPLOAD,
        [StringValue("S1CLOSURE")] 
        S1CLOSURE,
        [StringValue("PROJECTCLOSURE")]
        PROJECTCLOSURE,
        [StringValue("UNRECOMMEND")]
        UNRECOMMEND,
        [StringValue("RECOMMEND")]
        RECOMMEND,
        [StringValue("CHECKIN")]
        CHECKIN,
        [StringValue("RETURNTOMARKER")]
        RETURNTOMARKER,
        [StringValue("ESCALATE")]
        ESCALATE,
[StringValue("AUTHENTICATE")]
        AUTHENTICATE,
		[StringValue("PAGENAVIGATION")]
		PAGENAVIGATION

	}
}
